//tag::ref-doc[]
= Header Enricher Processor

Use the header-enricher app to add message headers.

The headers are provided in the form of new line delimited key value pairs, where the keys are the header names and the values are SpEL expressions.
For example `--headers='foo=payload.someProperty \n bar=payload.otherProperty'`

== Input

=== Headers

N/A

=== Payload

* Any

== Output

=== Headers

N/A

=== Payload

* Any

== Options

The **$$header-enricher$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$header.enricher.headers$$:: $$\n separated properties representing headers in which values are SpEL expressions, e.g foo='bar' \n baz=payload.baz$$ *($$Properties$$, default: `$$<none>$$`)*
$$header.enricher.overwrite$$:: $$set to true to overwrite any existing message headers$$ *($$Boolean$$, default: `$$false$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar header-enricher-processor.jar --headers='foo=payload.someProperty \n bar=payload.otherProperty'
```

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

//end::ref-doc[]
